/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CreateRoomResult = { 'invalidFormat' : string } |
  { 'duplicateId' : string } |
  { 'success' : string } |
  { 'unauthorized' : string };
export type ExternalBlob = Uint8Array;
export interface Photo {
  'photoBlob' : ExternalBlob,
  'photographer' : Principal,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRoom' : ActorMethod<[string], CreateRoomResult>,
  'deleteRoom' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPhotoAccess' : ActorMethod<[string], boolean>,
  'getPhotosByRoom' : ActorMethod<[string], Array<Photo>>,
  'getRoomCreator' : ActorMethod<[string], [] | [Principal]>,
  'getUserPhotos' : ActorMethod<[Principal], Array<Photo>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFactoryResetEnabledForUser' : ActorMethod<[Principal], boolean>,
  'isRoomPhotoAccessControlEnabled' : ActorMethod<[string], boolean>,
  'performFactoryReset' : ActorMethod<[Principal], undefined>,
  'ping' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'takePhoto' : ActorMethod<[string, ExternalBlob], undefined>,
  'toggleFactoryReset' : ActorMethod<[boolean], undefined>,
  'toggleRoomPhotoAccessControl' : ActorMethod<[string, boolean], undefined>,
  'verifyRoomCreator' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];